### ISSUE TITLE
[FR] Scroll into view on jump

### ISSUE THREAD

**Issue by ghost** [wenfangdu/vscode-jump#3]
Currently, on jump, only activeSelection (cursor) is updated.
It'd be great if it also tried to center editor view on the jump target.

Please share your opinions, did you find it annoying that after jumping editor is not scrolled to the jump target?
This behaviour is especially visible when using `"editor.cursorSurroundingLines": number` config option.

**Comment by wenfangdu** [comment]
In my experience, centering cursor position is a bit annoying, but if the user has set `"editor.cursorSurroundingLines"`, I think we should scroll up/down as they would with the arrow keys, so that the extension's behavior aligns with the default VSCode behavior.
