### ISSUE TITLE
Option for jump points at other symbols

### ISSUE THREAD

**Issue by mingteowork** [wenfangdu/vscode-jump#6]
When faced with trying to highlight an entire block including symbols, like this:

<img width="239" alt="image" src="https://user-images.githubusercontent.com/80294087/141224846-2406ebcd-6398-42c5-ac14-d53cdc0cd05b.png">

There's nothing for jump to hook onto, since it only hooks onto alpha characters.

Any way we can have an option to allow a list of hookable chars, so we could add symbols as we see fit?

**Comment by wenfangdu** [comment]
As the extension description suggests "
