### ISSUE TITLE
Feature: when holding shift, jump and select text

### ISSUE THREAD

**Issue by igorcafe** [wenfangdu/vscode-jump#7]
I would like to be able to:
1. Press ctrl + q q
2. When the letters show up, hold shift and type it
3. Jump the cursor to the new position, but making a selection between cursor starting and ending position

An example of the behavior:

https://user-images.githubusercontent.com/85039990/154717766-e8ad3663-d5df-4a5f-b81c-e1e925f9cc65.mp4

**Comment by igorcafe** [comment]
> 1. Press ctrl + q q

alt q q*

**Comment by wenfangdu** [comment]
@igoracmelo Hi, thanks for the feature request, selecting by pressing <kbd>shift</kbd> is currently not supported, you could use  [Select to the Start of a word](https://github.com/wenfangdu/vscode-jump#demo-select-to-the-start-of-a-word) and [Select to the End of a word](https://github.com/wenfangdu/vscode-jump#demo-select-to-the-end-of-a-word) as alternatives.
