### ISSUE TITLE
[error] properties `activationEvents` and `main` must both be specified or must both be omitted

### ISSUE THREAD

**Issue by opes** [wenfangdu/vscode-jump#8]
### Description

Within the last week or so, `Jump` has been deactivated and unusable on the latest VSCode Insiders due to the below error.

<img width="726" alt="Jump extension page displaying error" src="https://user-images.githubusercontent.com/2481552/223783849-f5231b76-98e4-4c4c-b9ce-d9ae1da05b28.png">

### Ouput
```
[error] [/Users/opes/.vscode-insiders/extensions/wenfangdu.jump-0.7.10]: properties `activationEvents` and `main` must both be specified or must both be omitted
```

### VSCode Info
```
Version: 1.77.0-insider (Universal)
Commit: b2ea6aa9fc4c9bebc3d2c2992a891244819dbccd
Date: 2023-03-08T05:22:25.379Z (11 hrs ago)
Electron: 19.1.11
Chromium: 102.0.5005.196
Node.js: 16.14.2
V8: 10.2.154.26-electron.0
OS: Darwin arm64 22.3.0
Sandboxed: Yes
```

### References
https://github.com/microsoft/vscode/issues/112532#issuecomment-769671614
Possibly related? https://github.com/microsoft/vscode/issues/176006

**Comment by wenfangdu** [comment]
Thank you for reporting! It seems like a regression bug on the VSCode side, I've filed [an issue](https://github.com/microsoft/vscode/issues/176602) for this, you can subscribe to that thread to get notified when it gets fixed.

For the time being, you can downgrade VSCode to v1.76 or use Jump v0.7.9.

**Comment by wenfangdu** [comment]
Fixed in https://github.com/microsoft/vscode/pull/177647, please update to the latest Insider.
