### ISSUE TITLE
Conflicts with vscode-neovim

### ISSUE THREAD

**Issue by ivanbarsukov** [wenfangdu/vscode-jump#9]
After adding the following settings to my `settings.json`
```
"extensions.experimental.affinity": {
  "asvetliakov.vscode-neovim": 1,
  "wenfangdu.jump":1,
}
```

I encounter two errors when attempting to use the jump command provided by the extension:
1. An error stating that the `command 'type' already exists`
2. A subsequent error `Cannot read properties of undefined (reading 'setDecorations')`

**Comment by wenfangdu** [comment]
@ivanbarsukov Hi, thanks for reporting, using the following config is enough:

```json
  "extensions.experimental.affinity": {
    "asvetliakov.vscode-neovim": 1
  },
```

**Comment by colinbr96** [comment]
If anyone else runs into this error while using the [Overtype](https://marketplace.visualstudio.com/items?itemName=DrMerfy.overtype) extension, you can paste this in `settings.json`:
```
"extensions.experimental.affinity": {
  "DrMerfy.overtype": 1
},
```
